### ISSUE TITLE
remove exe from history

### ISSUE THREAD

**Issue by 3052** [somombo/hlsdownloader#2]

**Comment by somombo** [comment]
why.. do you find this repo useful?

**Comment by 3052** [comment]
repo has no commits in several years, so it helps to archive it. that way if people are searching for a repo, they know this is no longer being developed

**Comment by somombo** [comment]
what kinds of commits would you like to see? .. I thought the project was done

**Comment by 3052** [comment]
well several issues, but first of all you should never store binary files in version control:

https://github.com/somombo/hlsdownloader/blob/master/hlsdownloader.exe

**Comment by somombo** [comment]
ok well.. feel free to PR

**Comment by 3052** [comment]
no archive repo please.

**Comment by somombo** [comment]
no PR please .. lol

**Comment by somombo** [comment]
> well several issues, but first of all you should never store binary files in version control:
> 
> https://github.com/somombo/hlsdownloader/blob/master/hlsdownloader.exe

I've deleted the exe for you @3052. how's that for active development? 😀

**Comment by 3052** [comment]
it needs to be removed from every single commit since it was first added:

https://github.com/somombo/hlsdownloader/commit/dd669eefd11de4161df3abb0935879bc062c1650

otherwise it still remains in the repo

**Comment by somombo** [comment]
why should anyone care if its in old commits?

**Comment by 3052** [comment]
because if you want to clone the repo, it is a larger size:

2.64 MB

**Comment by somombo** [comment]
done @3052

Exe is now at https://github.com/somombo/hlsdownloader/releases/download/v0.0.1-alpha/hlsdownloader.exe
